charts:
  generic:
    includes:
      - config.yaml
      - src: cronjobs.yaml
        dst: cronjob.yaml
      - deployment.yaml
      - src: hooks.yaml
        dst: hooks/job.yaml
      - src: hooks.config.yaml
        dst: hooks/config.yaml
      - src: hooks.secret.yaml
        dst: hooks/secret.yaml
      - hpa.yaml
      - ingress.yaml
      - pdb.yaml
      - secret.yaml
      - service.yaml
      - src: workers.yaml
        dst: worker.yaml
