[[ include './_helpers/_genid.yaml' ]]
[[ kind = 'ConfigMap' ]]
[[ name_suffix = '-hook' ]]
[[ extend './_layouts/vdata.yaml' ]]

[[ block pre ]]
{{- if and .Values.hooksConfig .Values.hooks }}
[[ end ]]

[[ block post ]]
{{- end }}
[[ end ]]

[[ block annotations ]]
[[ include './_helpers/hooks.annotations.yaml' ]]
[[ end ]]

[[ block annotations_vol ]]
[[ include './_helpers/hooks.annotations.yaml' ]]
[[ end ]]
